spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./config-server/config-repo/
            - file:./config-server/config-repo/{application}/
            - classpath:/config-repo/
            - classpath:/config-repo/{application}/

server:
  port: ${SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info
